window.forceData = [
    [
        { "id": 0, "info": "生物", "color": "red" },
        { "id": 1, "info": "原核生物", "color": "green" },
        { "id": 2, "info": "真核生物", "color": "green" },
        { "id": 3, "info": "动物界", "color": "#eea10d" },
        { "id": 4, "info": "真菌界", "color": "#eea10d" },
        { "id": 5, "info": "植物界", "color": "#eea10d" },
        { "id": 6, "info": "原生生物界", "color": "#eea10d" },
        { "id": 7, "info": "草本植物", "color": "pink" },
        { "id": 8, "info": "木本植物", "color": "pink" },
        { "id": 9, "info": "水生植物", "color": "pink" },
        { "id": 10, "info": "有脊椎动物", "color": "#b211ee" },
        { "id": 11, "info": "无脊椎动物", "color": "#b211ee" },
        { "id": 12, "info": "腔肠动物", "color": "#eb0682" },
        { "id": 13, "info": "扁形动物", "color": "#eb0682" },
        { "id": 14, "info": "线形动物", "color": "#eb0682" },
        { "id": 15, "info": "环节动物", "color": "#eb0682" },
        { "id": 16, "info": "两栖动物", "color": "gray" },
        { "id": 17, "info": "爬行动物", "color": "gray" },
        { "id": 18, "info": "哺乳动物", "color": "gray" },
        { "id": 19, "info": "鱼类", "color": "gray" },
        { "id": 20, "info": "鸟类", "color": "gray" },
        { "id": 21, "info": "软体动物", "color": "#eb0682" },
        { "id": 22, "info": "节肢动物", "color": "#eb0682" },
        { "id": 23, "info": "昆虫纲", "color": "#0c0107" },
        { "id": 24, "info": "甲壳纲", "color": "#0c0107" },
        { "id": 25, "info": "蛛形纲", "color": "#0c0107" },
        { "id": 26, "info": "多足纲", "color": "#0c0107" },
        { "id": 27, "info": "肢口纲", "color": "#0c0107" },
        { "id": 28, "info": "鼠妇", "color": "#0c0107" }
    ], [
        { "link": [0, 1], "length": 5 },
        { "link": [0, 2], "length": 5 },
        { "link": [2, 3], "length": 5 },
        { "link": [2, 4], "length": 5 },
        { "link": [2, 5], "length": 5 },
        { "link": [2, 6], "length": 5 },
        { "link": [5, 7], "length": 5 },
        { "link": [5, 8], "length": 5 },
        { "link": [5, 9], "length": 5 },
        { "link": [3, 11], "length": 5 },
        { "link": [3, 10], "length": 5 },
        { "link": [11, 12], "length": 5 },
        { "link": [11, 13], "length": 5 },
        { "link": [11, 14], "length": 5 },
        { "link": [11, 15], "length": 5 },
        { "link": [11, 21], "length": 5 },
        { "link": [11, 22], "length": 5 },
        { "link": [10, 16], "length": 5 },
        { "link": [10, 17], "length": 5 },
        { "link": [10, 18], "length": 5 },
        { "link": [10, 19], "length": 5 },
        { "link": [10, 20], "length": 5 },
        { "link": [22, 23], "length": 5 },
        { "link": [22, 24], "length": 5 },
        { "link": [22, 25], "length": 5 },
        { "link": [22, 26], "length": 5 },
        { "link": [22, 27], "length": 5 },
        { "link": [22, 28], "length": 5 },
    ]
];
